### ISSUE TITLE
cISO8583.unpack() functionality failing with example

### ISSUE THREAD

**Issue by add-ctrl** [chuksynaza/cISO8583#3]
When trying to unpack the example from the documentation (version 1.3.0), the following error occurs.

```javascript
ciso8583\src\main.js:68
        let theMTI = message.substr(0, 4);
                             ^

TypeError: message.substr is not a function
    at Main.unpack (.\node_modules\ciso8583\src\main.js:68:30)
    at iso8583Handler (myapp-test.js:21:32)
    at Socket.<anonymous> (myapp-test.js:49:7)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
```

**Comment by chuksynaza** [comment]
Hi @angsar, please what is the value of message?

There's a chance it is not a string and you cannot get the substring value of that.

Could you log and or share the value of the variable message from your code? Be sure not to expose any sensitive details.

Thanks.

**Comment by chuksynaza** [comment]
Hi @angsar, please let us know if you have resolved this or figured out if the variable message is a string or not.

Thanks.

**Comment by add-ctrl** [comment]
Hi **@chuksynaza**, thanks for your quick response. You're right, the variable was not a string and came across as an object. Below is the sample code, in case anyone ran into this issue.

**Background Information**
I was testing the cISO8583 unpacker using a client/server architecture. As such, when the client sends the data to the server, that data that's received on the socket is not of type *string* but *object*.

**Sample Client Code Snippet**
```javascript
const net = require('net');

let client = new net.Socket();
client.connect(8012, '127.0.0.1', () => {
  console.log('Connected');
  let isoMsg = "020042000400000000021612345678901234560609173030123109789ABC1000123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789";
  client.write(isoMsg); //sample ISO8583 from cISO8583 documentation
});

client.on('data', function(data) {
  console.log('Received: ' + data);
}); //data event

client.on('close', function() {
  console.log('Connection closed');
}); //close event
```

**Sample Server Code Snippet**
```javascript
const iso8583 = require('ciso8583');
const net = require('net');

function iso8583Handler(data, socket)
{
  console.log(`Data received: ${data}`);
  let iso8583Parser = new iso8583();

  console.log(`type of data: ${typeof data}`);
  console.log(JSON.stringify(data));
  let _str = data.toString('ascii'); //convert data object to string
  console.log(`str type: ${typeof _str} -> ${_str}`);
  let unpacked = iso8583Parser.unpack(_str); //before, I was calling unpack on 'data', which caused the issue

  console.log(unpacked);
  socket.write('da da dahhhh!'); //do something after parsing the data, etc
  socket.end();
} //fn iso8583Handler

let server = net.createServer((socket) => {
    socket.write('Welcome\n');

    socket.on('data', (data) => {
      iso8583Handler(data, socket);
    }); //data event
  }).on('error', (err) => {
    throw err;
}); //createServer

server.listen(8012);

```
